### ISSUE TITLE
Player Movement

### ISSUE THREAD

**Issue by Baneo** [MrFouss/Undruidic-Championship#1]

**Comment by Ezia** [comment]
C'est pas compris dans le controler de base ?

**Comment by MrFouss** [comment]
@Ezia It is, but we need to tweak it in order to have a custom movement behavior

**Comment by Baneo** [comment]
Bon pour la suite du personnage (ramasser les items et les utiliser on verra quand on les aura) c'est ouf de les faire a la main en code x)

**Comment by Ezia** [comment]
@Baneo "ouf" cool, ou "ouf" laborieux ? ^^

**Comment by Baneo** [comment]
Ouf laborieux, mais c'est aussi le temps de tout comprendre en C++, la je vais me concentrer sur le multi
